version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # 보안 비활성화
      - xpack.security.http.ssl.enabled=false  # HTTPS 비활성화
    networks:
      - datasource
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  ai:
    build: .
    container_name: ai
    restart: on-failure
    env_file:
      - .env
    networks:
      - dream
      - datasource
    ports:
      - "8000:8000"

volumes:
  esdata:
    driver: local

networks:
  dream:
    external: true
  datasource:
    external: true
